BLOCK_SIZE = 1024
NUM_LAYER = 12
NUM_HEAD = 12
NUM_EMBD = 768

# NOTE: If you don't have a GPU, you can try this
# config if you just want to see some progress.
# BLOCK_SIZE = 32
# NUM_LAYER = 4
# NUM_HEAD = 4
# NUM_EMBD = 64

BATCH_SIZE = 12

TRAINING_DATA_ROOT = "training_data_out"
TRAINING_DATA_NUMS = f"{TRAINING_DATA_ROOT}/nums.bin"
MODEL_DATA_ROOT = "model_data_out"
MISC_FILES_ROOT = "local"
TRAINING_FILES_LIST = f"{MISC_FILES_ROOT}/single_staff_files.log"

ANY_XML_FILE = (".xml", ".musicxml", ".xml.gz", ".musicxml.gz")

# Some parts of data prep are parallelized. This is the number of parallel
# processes to use. This can scale linearly with the number of cores you have.
PARALLELISM = 12

# https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/
# https://www.w3.org/2021/06/musicxml40/container-reference/elements/
ALLOWED_TAG_NAMES = {
    "accent",
    "accidental",
    "accidental-mark",
    "accidental-text",
    "accord",
    "accordion-high",
    "accordion-low",
    "accordion-middle",
    "accordion-registration",
    "actual-notes",
    "alter",
    "appearance",
    "arpeggiate",
    "arrow",
    "arrow-direction",
    "arrow-style",
    "arrowhead",
    "articulations",
    "artificial",
    "assess",
    "attributes",
    "backup",
    "bar-style",
    "barline",
    "barre",
    "base-pitch",
    "bass",
    "bass-alter",
    "bass-separator",
    "bass-step",
    "beam",
    "beat-repeat",
    "beat-type",
    "beat-unit",
    "beat-unit-dot",
    "beat-unit-tied",
    "beater",
    "beats",
    "bend",
    "bend-alter",
    "bookmark",
    "bottom-margin",
    "bracket",
    "brass-bend",
    "breath-mark",
    "caesura",
    "cancel",
    "capo",
    "chord",
    "chromatic",
    "circular-arrow",
    "clef",
    "clef-octave-change",
    "coda",
    "concert-score",
    "creator",
    "credit",
    "credit-image",
    "credit-symbol",
    "credit-type",
    "credit-words",
    "cue",
    "damp",
    "damp-all",
    "dashes",
    "defaults",
    "degree",
    "degree-alter",
    "degree-type",
    "degree-value",
    "delayed-inverted-turn",
    "delayed-turn",
    "detached-legato",
    "diatonic",
    "direction",
    "direction-type",
    "directive",
    "display-octave",
    "display-step",
    "display-text",
    "distance",
    "divisions",
    "doit",
    "dot",
    "double",
    "double-tongue",
    "down-bow",
    "duration",
    "dynamics",
    "effect",
    "elevation",
    "elision",
    "encoder",
    "encoding",
    "encoding-date",
    "encoding-description",
    "end-line",
    "end-paragraph",
    "ending",
    "ensemble",
    "except-voice",
    "extend",
    "eyeglasses",
    "f",
    "falloff",
    "feature",
    "fermata",
    "ff",
    "fff",
    "ffff",
    "fffff",
    "ffffff",
    "fifths",
    "figure",
    "figure-number",
    "figured-bass",
    "fingering",
    "fingernails",
    "first",
    "first-fret",
    "flip",
    "footnote",
    "for-part",
    "forward",
    "fp",
    "frame",
    "frame-frets",
    "frame-note",
    "frame-strings",
    "fret",
    "function",
    "fz",
    "glass",
    "glissando",
    "glyph",
    "golpe",
    "grace",
    "group",
    "group-abbreviation",
    "group-abbreviation-display",
    "group-barline",
    "group-link",
    "group-name",
    "group-name-display",
    "group-symbol",
    "group-time",
    "grouping",
    "half-muted",
    "hammer-on",
    "handbell",
    "harmon-closed",
    "harmon-mute",
    "harmonic",
    "harmony",
    "harp-pedals",
    "haydn",
    "heel",
    "hole",
    "hole-closed",
    "hole-shape",
    "hole-type",
    "humming",
    "identification",
    "image",
    "instrument",
    "instrument-abbreviation",
    "instrument-change",
    "instrument-link",
    "instrument-name",
    "instrument-sound",
    "instruments",
    "interchangeable",
    "inversion",
    "inverted-mordent",
    "inverted-turn",
    "inverted-vertical-turn",
    "ipa",
    "key",
    "key-accidental",
    "key-alter",
    "key-octave",
    "key-step",
    "kind",
    "laughing",
    "left-divider",
    "left-margin",
    "level",
    "line",
    "line-detail",
    "line-width",
    "link",
    "listen",
    "listening",
    "lyric",
    "lyric-font",
    "lyric-language",
    "measure",
    "measure",
    "measure-distance",
    "measure-layout",
    "measure-numbering",
    "measure-repeat",
    "measure-style",
    "membrane",
    "metal",
    "metronome",
    "metronome-arrows",
    "metronome-beam",
    "metronome-dot",
    "metronome-note",
    "metronome-relation",
    "metronome-tied",
    "metronome-tuplet",
    "metronome-type",
    "mf",
    "midi-bank",
    "midi-channel",
    "midi-device",
    "midi-instrument",
    "midi-name",
    "midi-program",
    "midi-unpitched",
    "millimeters",
    "miscellaneous",
    "miscellaneous-field",
    "mode",
    "mordent",
    "movement-number",
    "movement-title",
    "mp",
    "multiple-rest",
    "music-font",
    "mute",
    "n",
    "natural",
    "non-arpeggiate",
    "normal-dot",
    "normal-notes",
    "normal-type",
    "notations",
    "note",
    "note-size",
    "notehead",
    "notehead-text",
    "numeral",
    "numeral-alter",
    "numeral-fifths",
    "numeral-key",
    "numeral-mode",
    "numeral-root",
    "octave",
    "octave-change",
    "octave-shift",
    "offset",
    "open",
    "open-string",
    "opus",
    "ornaments",
    "other-appearance",
    "other-articulation",
    "other-direction",
    "other-dynamics",
    "other-listen",
    "other-listening",
    "other-notation",
    "other-ornament",
    "other-percussion",
    "other-play",
    "other-technical",
    "p",
    "page-height",
    "page-layout",
    "page-margins",
    "page-width",
    "pan",
    "part",
    "part",
    "part-abbreviation",
    "part-abbreviation-display",
    "part-clef",
    "part-group",
    "part-link",
    "part-list",
    "part-name",
    "part-name-display",
    "part-symbol",
    "part-transpose",
    "pedal",
    "pedal-alter",
    "pedal-step",
    "pedal-tuning",
    "per-minute",
    "percussion",
    "pf",
    "pitch",
    "pitched",
    "play",
    "player",
    "player-name",
    "plop",
    "pluck",
    "pp",
    "ppp",
    "pppp",
    "ppppp",
    "pppppp",
    "pre-bend",
    "prefix",
    "principal-voice",
    "print",
    "pull-off",
    "rehearsal",
    "relation",
    "release",
    "repeat",
    "rest",
    "rf",
    "rfz",
    "right-divider",
    "right-margin",
    "rights",
    "root",
    "root-alter",
    "root-step",
    "scaling",
    "schleifer",
    "scoop",
    "scordatura",
    "score-instrument",
    "score-part",
    "score-partwise",
    "score-timewise",
    "second",
    "segno",
    "semi-pitched",
    "senza-misura",
    "sf",
    "sffz",
    "sfp",
    "sfpp",
    "sfz",
    "sfzp",
    "shake",
    "sign",
    "slash",
    "slash-dot",
    "slash-type",
    "slide",
    "slur",
    "smear",
    "snap-pizzicato",
    "soft-accent",
    "software",
    "solo",
    "sound",
    "sounding-pitch",
    "source",
    "spiccato",
    "staccatissimo",
    "staccato",
    "staff",
    "staff-details",
    "staff-distance",
    "staff-divide",
    "staff-layout",
    "staff-lines",
    "staff-size",
    "staff-tuning",
    "staff-type",
    "staves",
    "stem",
    "step",
    "stick",
    "stick-location",
    "stick-material",
    "stick-type",
    "stopped",
    "straight",
    "stress",
    "string",
    "string-mute",
    "strong-accent",
    "suffix",
    "supports",
    "swing",
    "swing-style",
    "swing-type",
    "syllabic",
    "symbol",
    "sync",
    "system-distance",
    "system-dividers",
    "system-layout",
    "system-margins",
    "tap",
    "technical",
    "tenths",
    "tenuto",
    "text",
    "thumb-position",
    "tie",
    "tied",
    "time",
    "time-modification",
    "time-relation",
    "timpani",
    "toe",
    "top-margin",
    "top-system-distance",
    "touching-pitch",
    "transpose",
    "tremolo",
    "trill-mark",
    "triple-tongue",
    "tuning-alter",
    "tuning-octave",
    "tuning-step",
    "tuplet",
    "tuplet-actual",
    "tuplet-dot",
    "tuplet-normal",
    "tuplet-number",
    "tuplet-type",
    "turn",
    "type",
    "unpitched",
    "unstress",
    "up-bow",
    "vertical-turn",
    "virtual-instrument",
    "virtual-library",
    "virtual-name",
    "voice",
    "volume",
    "wait",
    "wavy-line",
    "wedge",
    "with-bar",
    "wood",
    "word-font",
    "words",
    "work",
    "work-number",
    "work-title",
    "container",
    "rootfile",
    "rootfiles",
}

TAG_NAMES_TO_IGNORE = {
    "identification",
    "defaults",
    "credit-words",
    "credit",
    "sound",
    "print",
    "part-list",
    "lyric",
    "words",
    "work",
    "movement-number",
    "movement-title",
    "harmony",  # although this could be interesting one day...?
    "direction",  # although this could be interesting one day...?
    "fingering",
    "ending",
    "repeat",
}

ATTRIBUTES_TO_IGNORE = {
    "default-y",
    "default-x",
    "width",
    "relative-x",
    "relative-y",
    "font-family",
    "font-size",
    "font-weight",
    "font-style",
    "color",
    "justify",
    "id",
    "number",
    "version",
    "dynamics",
    "{http://www.w3.org/XML/1998/namespace}id",
}

WHITELISTED_NUMS = {
    -9,
    -8,
    -7,
    -6,
    -5,
    -4,
    -3,
    -2,
    -1,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    12,
    13,
    14,
    15,
    16,
    18,
    20,
    24,
    30,
    32,
    36,
    40,
    45,
    48,
    60,
    64,
    72,
    80,
    90,
    96,
    120,
    128,
    144,
    160,
    180,
    192,
    240,
    264,
    268,
    320,
    360,
    384,
    480,
    720,
    960,
    1440,
    1680,
    1920,
}

INDENTS = {
    "<score-partwise>": 0,
    "<part>": 1,
    "<measure>": 2,
    '<measure implicit="yes">': 2,
    "<attributes>": 3,
    "<divisions>": 4,
    "<key>": 4,
    '<key print-object="no">': 4,
    "<fifths>": 5,
    '<time symbol="common">': 4,
    "<time>": 4,
    '<time symbol="cut">': 4,
    '<time print-object="no">': 4,
    "<beats>": 5,
    "<beat-type>": 5,
    "<staves>": 4,
    '<clef print-object="no">': 4,
    "<clef>": 4,
    "<sign>": 5,
    "<line>": 5,
    "<staff>": 4,
    '<note print-object="no">': 3,
    "<note>": 3,
    "<pitch>": 4,
    "<step>": 5,
    "<octave>": 5,
    "<duration>": 4,
    "<voice>": 4,
    '<type size="cue">': 4,
    "<type>": 4,
    "<stem>": 4,
    "<backup>": 3,
    "<rest>": 4,
    '<grace slash="yes">': 4,
    "<grace>": 4,
    "<accidental>": 4,
    '<accidental parentheses="yes">': 4,
    "<notations>": 4,
    '<slur type="stop">': 5,
    '<slur line-type="dashed" type="start" placement="above">': 5,
    '<slur line-type="dashed" type="start" placement="below">': 5,
    '<slur type="start" placement="above">': 5,
    '<slur type="start" placement="below">': 5,
    '<slur line-type="dotted" type="start" placement="below">': 5,
    '<slur line-type="dotted" type="start" placement="above">': 5,
    "<beam>": 4,
    "<time-modification>": 4,
    "<actual-notes>": 5,
    "<normal-notes>": 5,
    '<tuplet type="start" bracket="no">': 5,
    '<tuplet type="start" bracket="yes" show-number="none">': 5,
    '<tuplet type="start" bracket="no" show-number="both">': 5,
    '<tuplet type="stop">': 5,
    '<tuplet type="start" bracket="yes" show-number="both">': 5,
    '<tuplet type="start" bracket="no" show-number="none">': 5,
    '<tuplet type="start" bracket="yes">': 5,
    "<alter>": 5,
    "<chord>": 4,
    '<tie type="start">': 4,
    '<tie type="stop">': 4,
    '<tied type="start">': 5,
    '<tied type="start" line-type="dotted">': 5,
    '<tied type="start" line-type="dashed">': 5,
    '<tied type="stop">': 5,
    "<articulations>": 5,
    "<staccato>": 6,
    "<dot>": 4,
    "<ornaments>": 5,
    "<trill-mark>": 6,
    "<forward>": 3,
    '<barline location="right">': 3,
    '<barline location="left">': 3,
    "<bar-style>": 4,
    '<repeat direction="backward">': 4,
    '<repeat direction="backward" times="14">': 4,
    '<repeat direction="backward" times="8">': 4,
    '<repeat direction="forward">': 4,
    '<repeat direction="backward" times="10">': 4,
    '<repeat direction="backward" times="16">': 4,
    '<repeat direction="backward" times="20">': 4,
    '<repeat direction="backward" times="9">': 4,
    '<repeat direction="backward" times="7">': 4,
    '<repeat direction="backward" times="4">': 4,
    '<repeat direction="backward" times="15">': 4,
    '<repeat direction="backward" times="6">': 4,
    '<repeat direction="backward" times="50">': 4,
    '<repeat direction="backward" times="30">': 4,
    '<repeat direction="backward" times="5">': 4,
    '<repeat direction="backward" times="3">': 4,
    "<normal-type>": 5,
    "<mode>": 5,
    "<display-step>": 5,
    "<display-octave>": 5,
    '<fermata type="inverted">': 5,
    '<fermata type="upright">': 5,
    '<ending type="discontinue">': 4,
    '<ending type="stop">': 4,
    '<ending type="start">': 4,
    "<turn>": 6,
    "<cue>": 4,
    '<inverted-mordent long="yes" approach="below">': 6,
    '<inverted-mordent long="yes" departure="above">': 6,
    '<inverted-mordent long="yes">': 6,
    "<inverted-mordent>": 6,
    '<inverted-mordent long="yes" approach="above">': 6,
    '<inverted-mordent long="yes" departure="below">': 6,
    '<arpeggiate direction="down">': 5,
    "<arpeggiate>": 5,
    '<arpeggiate direction="up">': 5,
    "<detached-legato>": 6,
    "<scoop>": 6,
    "<tenuto>": 6,
    "<accent>": 6,
    "<doit>": 6,
    "<inverted-turn>": 6,
    "<clef-octave-change>": 5,
    "<transpose>": 4,
    "<diatonic>": 5,
    "<chromatic>": 5,
    "<technical>": 5,
    "<string>": 6,
    '<tremolo type="stop">': 6,
    '<tremolo type="start">': 6,
    '<tremolo type="single">': 6,
    '<extend type="start">': 5,
    '<extend type="continue">': 5,
    '<extend type="stop">': 5,
    "<down-bow>": 6,
    "<staccatissimo>": 6,
    '<mordent long="yes">': 6,
    '<mordent long="yes" approach="below">': 6,
    '<mordent long="yes" approach="above">': 6,
    "<mordent>": 6,
    "<caesura>": 6,
    '<notehead filled="yes">': 4,
    '<notehead parentheses="yes">': 4,
    "<notehead>": 4,
    '<notehead filled="no">': 4,
    "<up-bow>": 6,
    "<breath-mark>": 6,
    "<measure-style>": 4,
    "<multiple-rest>": 5,
    "<octave-change>": 5,
    "<movement-number>": 1,
    "<figured-bass>": 3,
    '<figured-bass parentheses="yes">': 3,
    "<figure>": 4,
    "<figure-number>": 5,
    "<suffix>": 5,
    "<prefix>": 5,
    "<unpitched>": 4,
    "<instrument>": 4,
    '<glissando line-type="wavy" type="stop">': 5,
    '<glissando line-type="wavy" type="start">': 5,
    '<slide line-type="solid" type="stop">': 5,
    '<slide line-type="solid" type="start">': 5,
    "<staff-details>": 4,
    "<staff-lines>": 5,
    '<strong-accent type="down">': 6,
    '<strong-accent type="up">': 6,
    "<stopped>": 6,
    "<open-string>": 6,
    '<wavy-line type="start">': 6,
    '<wavy-line type="stop">': 6,
    "<instruments>": 4,
    "<falloff>": 6,
    '<staff-tuning line="2">': 5,
    '<staff-tuning line="3">': 5,
    '<staff-tuning line="6">': 5,
    '<staff-tuning line="5">': 5,
    '<staff-tuning line="4">': 5,
    '<staff-tuning line="1">': 5,
    '<staff-tuning line="7">': 5,
    "<tuning-step>": 6,
    "<tuning-octave>": 6,
    "<fret>": 6,
    "<pluck>": 6,
    '<non-arpeggiate type="bottom">': 5,
    '<non-arpeggiate type="top">': 5,
    "<key-step>": 5,
    "<key-alter>": 5,
    "<key-accidental>": 5,
    "<plop>": 6,
    "<snap-pizzicato>": 6,
    "<tuning-alter>": 6,
    "<thumb-position>": 6,
    "<schleifer>": 6,
}
